### PR TITLE
feat: Add support for the new Pre-Translate Efficiency Report

### LINKED ISSUE #57: Reports APIs: Add support for the new Pre-Translate Efficiency Report
The new Pre-Translate Efficiency Report is now available in the Crowdin Reports API. It is used to assess the effectiveness of pre-translation methods.

**Things to do:**

- Add support for the new report to this API client.
- Remove the obsolete report types (see the API documentation for the list of relevant types).

**References:**

- [Generate Report](https://support.crowdin.com/developer/api/v2/#tag/Reports/operation/api.projects.reports.post)

### PR DESCRIPTION
**Pull request by jameskim0987**
Resolves #57 

Changes made in this PR:
1. add `PreTranslateEfficiencySchema` struct and its respective `ValidateSchema()`
2. add const `ReportPreTranslateEfficiency`
3. add valid testcase for PreTranslateEfficiencySchema.

### CODE REVIEW

**Comment by jameskim0987** [comment]
Question for the main contributors -- I observed that there aren't any negative test cases. Would it be worth adding? (ex: https://github.com/crowdin/crowdin-api-client-go/pull/65/files#diff-6aff06001ee42c02818cd8fd62715899b7c539d3bf582ee9a750e93147317d56R110 )

**Review by andrii-bodnar — APPROVED** [review]
@jameskim0987 thank you!

**Comment by andrii-bodnar** [comment]
@vorobeyme what do you think about negative test cases?

**Comment by jameskim0987** [comment]
@vorobeyme I think checking if the required fields are missing is fine. I was thinking more in terms of input validation. For example, 

 ```
// Split into categories by edit distance.
 PostEditingCategories []string `json:"postEditingCategories,omitempty"`
```

From the API docs example, it looks like for `PostEditingCategories` it has the value [ "0-10" ] which led me think if we should validate the string format ( I'm not exactly sure what "0-10" signifies nor the entire acceptable format though ).

**Comment by jameskim0987** [comment]
@vorobeyme Thanks for your input. I will remove the `TODO` comment since I think we are set then.
@andrii-bodnar let me know if this PR is in good shape

**Pull request merged**
